import { vueInfractionsEdit } from "../controleur/class_infractions_edit";

vueInfractionsEdit.init({
	
	edtInf: document.querySelector('[id=edtInf]')
	, edtDateInf: document.querySelector('[id=edtDateInf]')
	, edtImmatInf: document.querySelector('[id=edtImmatInf]')
	, edtVehiculeInf: document.querySelector('[id=edtVehiculeInf]')
	, edtPropVeh: document.querySelector('[id=edtPropVeh]')
	, edtDateImmatInf: document.querySelector('[id=edtDateImmatInf]')
	, edtDatePermisVeh: document.querySelector('[id=edtDatePermisVeh]')
	, edtPermisInf: document.querySelector('[id=edtPermisInf]')
	, edtPropInf: document.querySelector('[id=edtPropInf]')
	, edtDatePermisInf: document.querySelector('[id=edtDatePermisInf]')

	, divInfractionsTitre: document.querySelector('[id=div_infractions_titre]')
	, divInfractionsDetail: document.querySelector('[id=div_infractions_detail]')
	, lblErreurNum: document.querySelector('[id=lbl_erreur_num]')
	, edtInfractionsNum: document.querySelector('[id=edt_infractions_num]')
	, edtInfractionsLib: document.querySelector('[id=edt_infractions_lib]')
	, edtInfractionsEtage: document.querySelector('[id=edt_infractions_etage]')
	, lblErreurEtage: document.querySelector('[id=lbl_erreur_etage]')
	, lblErreurDept: document.querySelector('[id=lbl_erreur_dept]')
	, edtInfractionsCodeDept: document.querySelector('[id=edt_infractions_codedept]')
	, lblInfractionsDetailDept: document.querySelector('[id=lbl_infractions_detail_dept]')
	, lblErreurEquipt: document.querySelector('[id=lbl_erreur_equipt]')
	, divDelits: document.querySelector('[id=div_delits]')
	, lblDelitsTotaux: document.querySelector('[id=lbl_delits_totaux]')
	, tableDelits: document.querySelector('[id=table_delits]')
	, btnDelitAjouter: document.querySelector('[id=btn_delit_ajouter]')
	, divDelitEdit: document.querySelector('[id=div_delit_edit]')
	, listeDelit: document.querySelector('[id=select_delit]')
	, lblErreurListeDelit: document.querySelector('[id=lbl_erreur_select_delit]')
	, edtDelitMontant: document.querySelector('[id=edt_delit_montant]')
	, lblErreurQte: document.querySelector('[id=lbl_erreur_qte]')
	, btnDelitValider: document.querySelector('[id=btn_delit_valider]')
	, btnDelitAnnuler: document.querySelector('[id=btn_delit_annuler]')
	, btnInfractionsAnnuler: document.querySelector('[id=btn_infractions_annuler]')
	, btnInfractionsValider: document.querySelector('[id=btn_infractions_valider]')
});